name: Docker Image
on:
  push:
    branches:
      - main
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin
      - name: Build Docker image
        run: docker build -t codelev/cpu-stress:latest .
      - name: Push Docker image
        run: docker push codelev/cpu-stress:latest
